name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: typst-community/setup-typst@v4

      - name: install Merriweather font
        run: |
          mkdir -p ~/.local/share/fonts
          curl -fsSL https://github.com/SorkinType/Merriweather/archive/refs/heads/master.zip -o merriweather.zip
          unzip -q merriweather.zip
          cp Merriweather-master/fonts/otf/*.otf ~/.local/share/fonts/
          fc-cache -f -v

      - name: compile résumé
        run: typst compile resume/resume.typ static/daniel-young-résumé.pdf

      - name: zola deploy
        uses: shalzz/zola-deploy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
