name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - trunk
    paths-ignore:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install typst
        run: cargo install typst-cli

      - name: compile résumé
        run: typst compile resume/resume.typ static/daniel-young-résumé.pdf

      - name: zola deploy
        uses: shalzz/zola-deploy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
