name: publish

on:
  push:
    branches:
      - trunk
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shalzz/zola-deploy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
